"""Performance metrics with static and runtime profiling signals.

Runtime signals are loaded from ``tmp/perf_metrics/runtime_metrics_*.json`` files
generated by ``shared.perf_metrics``. These allow quality scoring to include:
- API latency penalty with exponential growth after 10 ms
- Time deviation detection for modules/functions/methods
- Memory deviation detection for modules/functions/methods
"""

import ast
import json
import math
import statistics
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class FilePerformanceMetrics:
    file_path: str
    loc: int  # lines of code (non-blank, non-comment)
    total_lines: int
    num_imports: int
    num_functions: int
    num_classes: int
    max_function_length: int
    avg_function_length: float
    long_functions: List[Tuple[str, int, int]]  # (name, line, length)


@dataclass
class PerformanceReport:
    file_metrics: List[FilePerformanceMetrics] = field(default_factory=list)
    import_time_seconds: Optional[float] = None
    peak_memory_mb: Optional[float] = None
    runtime_measurements_count: int = 0
    api_measurements_count: int = 0
    api_time_penalty: float = 0.0
    api_time_score: float = 1.0
    execution_time_deviation_score: float = 1.0
    memory_deviation_score: float = 1.0
    overall_runtime_performance_score: float = 1.0
    time_outlier_metrics: List[str] = field(default_factory=list)
    memory_outlier_metrics: List[str] = field(default_factory=list)

    @property
    def total_loc(self) -> int:
        return sum(f.loc for f in self.file_metrics)

    @property
    def total_lines(self) -> int:
        return sum(f.total_lines for f in self.file_metrics)

    @property
    def avg_function_length(self) -> float:
        lengths = []
        for f in self.file_metrics:
            lengths.append(f.avg_function_length)
        return sum(lengths) / len(lengths) if lengths else 0.0

    @property
    def long_function_count(self) -> int:
        return sum(len(f.long_functions) for f in self.file_metrics)

    @property
    def total_imports(self) -> int:
        return sum(f.num_imports for f in self.file_metrics)


# ---------------------------------------------------------------------------
# Static analysis
# ---------------------------------------------------------------------------

LONG_FUNCTION_THRESHOLD = 50  # lines
RUNTIME_METRICS_GLOB = "runtime_metrics_*.json"
RUNTIME_METRICS_DIR = Path("tmp") / "perf_metrics"


def _count_loc(source: str) -> int:
    """Count non-blank, non-comment lines."""
    count = 0
    for line in source.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            count += 1
    return count


def _function_lengths(tree: ast.AST) -> List[Tuple[str, int, int]]:
    """Return (name, lineno, length) for every function/method."""
    results: List[Tuple[str, int, int]] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # Approximate length from first to last line
            end = getattr(node, "end_lineno", node.lineno)
            length = end - node.lineno + 1
            results.append((node.name, node.lineno, length))
    return results


def _count_imports(tree: ast.AST) -> int:
    count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            count += 1
    return count


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def _safe_mean(values: List[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def _api_time_penalty_ms(response_ms: float) -> float:
    """API penalty function:

    - response < 10 ms: penalty = 0
    - response >= 10 ms: exponentially increasing penalty approaching 1.0
    """
    if response_ms < 10.0:
        return 0.0
    return _clamp01(1.0 - math.exp(-(response_ms - 10.0) / 45.0))


def _compute_deviation_score(values_by_metric: Dict[str, float]) -> Tuple[float, List[str]]:
    """Return (score, outlier_names) from high-side deviation analysis."""
    if len(values_by_metric) < 3:
        return 1.0, []

    values = list(values_by_metric.values())
    std = statistics.pstdev(values)
    if std <= 1e-9:
        return 1.0, []

    avg = _safe_mean(values)
    threshold = avg + (2.0 * std)
    outliers = [(name, value) for name, value in values_by_metric.items() if value > threshold]
    if not outliers:
        return 1.0, []

    outlier_ratio = len(outliers) / len(values_by_metric)
    excess = [
        (value - threshold) / max(threshold, 1e-6)
        for _, value in outliers
    ]
    excess_factor = _safe_mean(excess)
    penalty = _clamp01((0.75 * outlier_ratio) + (0.25 * excess_factor))
    score = _clamp01(1.0 - penalty)
    outlier_names = [name for name, _ in sorted(outliers, key=lambda x: x[1], reverse=True)]
    return score, outlier_names


def _guess_project_root(from_file: Path) -> Optional[Path]:
    current = from_file.resolve().parent
    for candidate in [current, *current.parents]:
        if (candidate / "docker-compose.yml").exists():
            return candidate
    return None


def _load_runtime_metric_entries(project_root: Path) -> List[Dict[str, object]]:
    metrics_dir = project_root / RUNTIME_METRICS_DIR
    if not metrics_dir.is_dir():
        return []

    entries: List[Dict[str, object]] = []
    for metric_file in sorted(metrics_dir.glob(RUNTIME_METRICS_GLOB)):
        try:
            payload = json.loads(metric_file.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        items = payload.get("items") if isinstance(payload, dict) else None
        if not isinstance(items, list):
            continue
        for item in items:
            if isinstance(item, dict):
                entries.append(item)
    return entries


def _aggregate_runtime(entries: List[Dict[str, object]]) -> Dict[str, Dict[str, object]]:
    aggregated: Dict[str, Dict[str, object]] = {}
    for entry in entries:
        metric_name = entry.get("metric_name")
        kind = entry.get("kind")
        calls = entry.get("calls")
        total_ms = entry.get("total_ms")
        total_memory_kb = entry.get("total_memory_kb")
        if not isinstance(metric_name, str) or not isinstance(kind, str):
            continue
        if not isinstance(calls, (int, float)) or calls <= 0:
            continue
        if not isinstance(total_ms, (int, float)):
            continue
        if not isinstance(total_memory_kb, (int, float)):
            total_memory_kb = 0.0

        agg = aggregated.setdefault(
            metric_name,
            {"calls": 0.0, "total_ms": 0.0, "total_memory_kb": 0.0, "kind_name": kind},
        )
        agg["calls"] += float(calls)
        agg["total_ms"] += float(total_ms)
        agg["total_memory_kb"] += float(total_memory_kb)
        agg["kind_name"] = kind
    return aggregated


def analyze_file_performance(file_path: Path) -> FilePerformanceMetrics:
    source = file_path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source, filename=str(file_path))
    except SyntaxError:
        return FilePerformanceMetrics(
            file_path=str(file_path),
            loc=0, total_lines=0, num_imports=0,
            num_functions=0, num_classes=0,
            max_function_length=0, avg_function_length=0.0,
            long_functions=[],
        )

    func_lengths = _function_lengths(tree)
    lengths_only = [l for _, _, l in func_lengths]
    num_classes = sum(1 for n in ast.walk(tree) if isinstance(n, ast.ClassDef))
    long_funcs = [(n, ln, l) for n, ln, l in func_lengths if l > LONG_FUNCTION_THRESHOLD]

    return FilePerformanceMetrics(
        file_path=str(file_path),
        loc=_count_loc(source),
        total_lines=len(source.splitlines()),
        num_imports=_count_imports(tree),
        num_functions=len(func_lengths),
        num_classes=num_classes,
        max_function_length=max(lengths_only) if lengths_only else 0,
        avg_function_length=sum(lengths_only) / len(lengths_only) if lengths_only else 0.0,
        long_functions=long_funcs,
    )


def analyze_performance(
    source_files: List[Path],
    project_root: Optional[Path] = None,
) -> PerformanceReport:
    """Analyze performance-related metrics across all source files."""
    report = PerformanceReport()
    for fp in source_files:
        report.file_metrics.append(analyze_file_performance(fp))

    # Optional: measure import time of the shared module
    try:
        start = time.perf_counter()
        # Try importing the lightest shared module to gauge import overhead
        subprocess.run(
            [sys.executable, "-c", "import ast, json, pathlib"],
            capture_output=True,
            timeout=10,
        )
        report.import_time_seconds = round(time.perf_counter() - start, 4)
    except Exception:
        report.import_time_seconds = None

    # Optional: measure peak memory of the analysis itself
    try:
        import resource
        usage = resource.getrusage(resource.RUSAGE_SELF)
        report.peak_memory_mb = round(usage.ru_maxrss / 1024, 2)  # Linux: KB -> MB
    except Exception:
        report.peak_memory_mb = None

    if project_root is None and source_files:
        project_root = _guess_project_root(source_files[0])

    if project_root is not None:
        runtime_entries = _load_runtime_metric_entries(project_root)
        runtime_aggregated = _aggregate_runtime(runtime_entries)

        report.runtime_measurements_count = len(runtime_aggregated)

        if runtime_aggregated:
            api_avg_ms: List[float] = []
            time_values: Dict[str, float] = {}
            memory_values: Dict[str, float] = {}

            for metric_name, metric_data in runtime_aggregated.items():
                calls = float(metric_data.get("calls", 0.0))
                if calls <= 0:
                    continue
                total_ms = float(metric_data.get("total_ms", 0.0))
                total_memory_kb = float(metric_data.get("total_memory_kb", 0.0))
                kind_name = metric_data.get("kind_name")

                avg_ms = total_ms / calls
                avg_memory_kb = total_memory_kb / calls

                time_values[metric_name] = avg_ms
                if avg_memory_kb > 0:
                    memory_values[metric_name] = avg_memory_kb

                if kind_name == "api":
                    api_avg_ms.append(avg_ms)

            report.api_measurements_count = len(api_avg_ms)
            if api_avg_ms:
                penalties = [_api_time_penalty_ms(v) for v in api_avg_ms]
                report.api_time_penalty = round(_safe_mean(penalties), 6)
                report.api_time_score = round(_clamp01(1.0 - report.api_time_penalty), 6)

            time_dev_score, time_outliers = _compute_deviation_score(time_values)
            report.execution_time_deviation_score = round(time_dev_score, 6)
            report.time_outlier_metrics = time_outliers[:10]

            memory_dev_score, memory_outliers = _compute_deviation_score(memory_values)
            report.memory_deviation_score = round(memory_dev_score, 6)
            report.memory_outlier_metrics = memory_outliers[:10]

            # Keep deviation metrics at 20% total influence (10% each).
            report.overall_runtime_performance_score = round(
                _clamp01(
                    (0.80 * report.api_time_score)
                    + (0.10 * report.execution_time_deviation_score)
                    + (0.10 * report.memory_deviation_score)
                ),
                6,
            )

    return report
